manifest = "ab308d1d2bd72c88923e5184c995452c1c30db1257d93aad6265c786d83605a8"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.50.0" ]
revision = "0af936e42c3db7c0f8a63e21265a645b70abb9cb"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.50.0" ]
revision = "7a95ba736b9be014028bf95deeeb5ccb06f8588b"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.50.0" ]
revision = "af76a5aef78b01d8e4b520133233a12fd69fe304"
