manifest = "a81f5dfba661f610476037f0258f015b89a65ac2b620630a3c834d5436dd2dae"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.42.0" ]
revision = "bdbfd4f7cb2eb6f0a1d87672c0564f4909c4cb20"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.42.0" ]
revision = "ad64e4e9f85cad0ed501c3eaf0faba2a9bfc3dc3"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.42.0" ]
revision = "d3cb1586ec0bb62cbe3cbfb8eadf4f759379fce6"
