targets = [ "//:mpl" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.32.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
version = "1.32.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.32.0"
